name: 
  - scampi-preprocessing
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9.12
  - openslide
  - ultralytics=8.0.154
  - pip
  - pip:
    - opencv-python==4.8.0.74
    - openslide-python==1.1.2
    - scikit-image==0.19.2
    - tensorflow-macos==2.11.0
    - tensorflow-metal==0.7.1
    - yolov5==7.0.12
